name: read_reminder
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  #material
  cupertino_icons: ^1.0.2

  #Firebase
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2
  google_sign_in: ^6.1.4
  #StateManagement
  provider: ^6.0.5
  #Fonts
  google_fonts: ^4.0.0
  font_awesome_flutter: ^10.4.0




dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/Firefly a cute orange cat in a clock and a light purple circle background 42614.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - lib/assets/splash_img.jpg
    - lib/assets/Firefly a cute orange cat in a clock and a light purple circle background 42614.jpg
    - lib/assets/aPngtreeahand_drawn_cute_cat_reading_4361091.png
    - lib/assets/icons/ic_add.png
    - lib/assets/icons/ic_book.png
    - lib/assets/icons/ic_coin.png
    - lib/assets/icons/ic_notif.png
    - lib/assets/icons/ic_profile.png
    - lib/assets/icons/ic_time.png
    - lib/assets/background/bg_profile.png
    - lib/assets/timer.png
    - lib/assets/aPngtreeahand_drawn_cute_cat_reading_4361091.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
          - asset: lib/assets/Lato/Lato-Regular.ttf
          - asset: lib/assets/Lato/Lato-Bold.ttf
          - asset: lib/assets/Lato/Lato-Italic.ttf



